SELECT * FROM <skupstina/dokument/akt>
WHERE {
	?documentId <http://parlament.gov.rs/rs.ac.uns.ftn.model.pred/napravio> ?user .
	?documentId <http://parlament.gov.rs/rs.ac.uns.ftn.model.pred/imeDokumenta> ?documentName .
  ?documentId <http://parlament.gov.rs/rs.ac.uns.ftn.model.pred/datumKreiranja> ?dateCreated .
  ?documentId <http://parlament.gov.rs/rs.ac.uns.ftn.model.pred/datumAzuriranja> ?dateModified .
}
