security:
  basic:
    enabled: false
spring:
  profiles:
    active:
  application:
    name: XML SIIT

server:
  port: 8080


# Application specific properties
xmlsiit-app:
  security:
    token: "Authorization"
    secret: "my-very-little-secret"




# Marklogic properties

marklogic:
  connectivity:
      user: "rest-writer"
      password: "x"
      host: "localhost"
      port: 8011
      databaseName: "xmlsiit"
debug: true







